### ISSUE TITLE
Feat: 대화 시스템 개발 / 인게임 연결

### ISSUE THREAD

**Issue by ccmuk58** [The-Day-In-1984/1984_Project#123]
# 대화 시스템 인게임 연결

## Todo

- [x] UI 구성
- [x] 텍스트 연결
- [x] img path 연결
- [x] 텍스트 로직 작성
- [x] 선택지 로직 작성
- [x] 씬 연결
