### ISSUE TITLE
Feat: Prototype Game System

### ISSUE THREAD

**Issue by fkdl0048** [The-Day-In-1984/1984_Project#132]
# Feature: 게임 시스템

세이브/로드, 인게임에 사용되는 데이터, 씬 전환 등

## Description

- https://github.com/The-Day-In-1984/1984_Project/issues/129#event-9277958444
- https://github.com/The-Day-In-1984/1984_Project/issues/128

## Todo

- [x] UI 모델 구현
- [x] 씬 전환 상태 패턴 임시 구현
- [x] 충성도 게이지 시스템 구현
- [ ] 미션과 연결하여 실패/성공 바인딩
- [x] 임시 리소스 슬라이더 바 적용

## ETC

그 외
