### ISSUE TITLE
Feat: 플랫포머 맵

### ISSUE THREAD

**Issue by kyoonge** [The-Day-In-1984/1984_Project#133]
# Feature: 프로토타입을 위한 플랫포머 맵 구현하기

## Description
기획: #103
아트: #130  

## Todo

- [ ] 1일 차 배경 및 미션 오브젝트 추가
- [ ] 카메라 제한 두기
- [ ] 텔레스크린 오브젝트 추가

## ETC

그 외
