### ISSUE TITLE
Feat: 임무/게임시스템 개발 리스트

### ISSUE THREAD

**Issue by fkdl0048** [The-Day-In-1984/1984_Project#28]
# Feature: 임무 시스템 

프랫포머 도중 상호작용을 통한 포인트 앤 클릭 미션

ex) 어몽어스

- https://github.com/The-Day-In-1984/1984_Project/issues/122

프레임 설계

## Description

1. 플레이어가 상호작용을 통해 미션을 진행함
2. 미션은 마우스 클릭으로 진행되며 1984에 맞는 다양한 미션이 존재
3. 미션 성공여부에 따른 평판게이지 증감(이후에 dataSystem쪽으로 빠짐)
4. 다양한 미션을 정규화를 통해 데이터 테이블로 관리

## Todo

- [x] 미션 레퍼런스 조사 후 기획이랑 논의
- [x] #41(~ 03/27)
- [x] https://github.com/The-Day-In-1984/1984_Project/issues/131
- [x] https://github.com/The-Day-In-1984/1984_Project/issues/132

일차로 구분하여 작업

- [ ] 2일차 미션작업

## 시스템 참고 내용

미션은 그냥 실패/성공으로 구분
미션의 형태는 지금과 같이 마우스 이벤트

c타입 미션 추가: 해당 오브젝트 접촉 시

### 논의 사항

1. 미션 등장연출
2. 원하는 이펙
