### ISSUE TITLE
Feat: 대화 시스템 개발 리스트

### ISSUE THREAD

**Issue by ccmuk58** [The-Day-In-1984/1984_Project#29]
# Feature: 대화 시스템(Dialogue System)

- 대화 및 선택지 기능 구현을 위한 툴
- 위 툴을 기반한 스토리 시스템

## Description

- 대화 및 분기 시스템 에디터 구현
- 대화 및 분기 데이터 관리
- 분기에 따른 대화 출력

## Todo

- [ ] 대화 시스템 개념 확립
- [ ] 데이터 관리 관련 조사
- [ ] Dialouge System 오픈 소스 분석
- [ ] 프로토타입 구현

## ETC

추가 예정 . .
