### ISSUE TITLE
Feat: 캐릭터 조작

### ISSUE THREAD

**Issue by kyoonge** [The-Day-In-1984/1984_Project#62]
# 캐릭터 조작

 AD 방향 조작, 스페이스바 점프, WS 사다리 액션 구현

## Todo

- [x] AD 방향 조작, 스페이스바 점프( 긴점프, 짧은 점프 )
- [x] WS 사다리 액션
- [ ] 조작감 디테일 추가
- [ ] 구조 재정비

## 고민해보자

- 점프 유형 정하기 ( 긴점프, 짧은 점프, 연속 점프 등 다양한 점프 형태가 존재함.. 어떤게 필요할까? )
- 속도 및 점프힘 조절
- 스크립터블 오브젝트 생성
- 디테일 어느 정도로 필요한지..... 참고: https://youtu.be/3sWTzMsmdx8

**Comment by fkdl0048** [comment]
1. 저도 점프 유형이 가장 걱정이 되는데 액션게임이 아니라 정적인 형태도 좋을 것 같아요 기획이랑 이야기가 필요해보입니다..!

이럴 땐 캐릭터 동작에 따른 Discussion을 파서 기획 호출 후 이야기를 해보시는 것을 추천..

**Comment by dkssu46** [comment]
점프 유형에 관해서는 액션성을 중시한 게임이 아니다보니, 아주 디테일하게 세분화할 필요는 없을 것 같아!
단순히 바라보는 방향으로 점프하는 방식 or 점프하는 순간의 키보드 입력에 따라서 힘을 받는 방식 정도에서만 선택하면 되지 않을까 싶은데, 좀 더 고민해보고 전달할 수 있도록 할게
이동속도, 점프속도, 점프력 등은 레벨 밸런싱이랑 깊이 연결된 부분이니, 변수로 빼놓고 일단은 임시로 값을 넣어서 테스트해줄 수 있을까? 마지막 QA 단계에서 수정될 일이 생길 것 같아!

**Comment by kyoonge** [comment]
오오 조아요 감삼다
일단 변수값들은 임의로 해놓는 걸로 하고
점프는 Discussion 파놓을게!~~
